version: '3.3'

networks:
  sipag-net:

services:
  database:
    container_name: database
    image: mysql
    restart: unless-stopped
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    networks:
      - sipag-net

  phpmyadmin:
    container_name: phpmyadmin-database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_PORT=3306
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - PMA_ARBITRARY=1
    networks:
      - sipag-net

  php:
    container_name: php_fpm
    image: hex4coder/php-laravel
    privileged: true
    volumes:
      - ./sptsp:/var/www/html
    ports:
      - 9000:9000
      - 8000:8000
      - 5173:5173
    networks:
      - sipag-net

  webserver:
    container_name: webserver
    image: nginx:stable-alpine
    volumes:
      - ./sptsp:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php
      - database
      - phpmyadmin
    networks:
      - sipag-net